$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - node_modules
  - bun.lockb
  - .tsbuildinfo
  - .gitignore
  - .next
  - drizzle
  - '**/*.svg'
  - .vscode/extensions.json
  - .devcontainer
  - public
  - tsconfig.tsbuildinfo
  - branch_out
words:
  - activecampaign
  - aeiou
  - Arcjet
  - asana
  - autopilotmail
  - autoresponder
  - bcdfghj
  - bigcommerce
  - bullmq
  - callees
  - classname
  - clsx
  - commitlint
  - compat
  - constantcontact
  - customerservice
  - esbenp
  - facebookmail
  - freshdesk
  - frontmatter
  - gtag
  - healthcheck
  - helpdesk
  - helpscout
  - hookform
  - hubspot
  - ianvs
  - ixahmedxi
  - ixahmedxii
  - jiti
  - lockb
  - lucide
  - mailchimp
  - mailgun
  - marketo
  - mitigations
  - neondatabase
  - nextjs
  - nosniff
  - noreplys
  - packagejson
  - paralleldrive
  - pinterest
  - pipedrive
  - pkill
  - Posthog
  - postmarkapp
  - ratelimit
  - redditmail
  - refetches
  - Registrator
  - Runbook
  - SAMEORIGIN
  - sendgrid
  - sendinblue
  - serviceworker
  - setex
  - Shadcn
  - Signin
  - Signup
  - Sonner
  - sslmode
  - superjson
  - tailwindcss
  - tanstack
  - tawk
  - timeago
  - Todos
  - trpc
  - tsbuildinfo
  - tseslint
  - Turbopack
  - typecheck
  - Uploadthing
  - Upstash
  - usehooks
  - xlcmsua
